[package]
name = "template"
version = "0.3.78"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
topology = { path = "../topology" }

# Templates
anyhow = { workspace = true }
askama = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_yaml = "0.9.34"
serde_json = { workspace = true }

# IP Addressing
ipnet = { workspace = true }

[dev-dependencies]
urlencoding = "2.1"
