#! /usr/bin/bash

set -euo pipefail

source  sherpad.env
cargo build -p sherpad
sudo setcap cap_net_admin,cap_net_raw+ep target/debug/sherpad
sudo -u sherpa SHERPA_ADMIN_PASSWORD=$SHERPA_ADMIN_PASSWORD SHERPA_DB_PASSWORD=$SHERPA_DB_PASSWORD target/debug/sherpad start --foreground
