#! /usr/bin/bash

set -euo pipefail

cargo build -p sherpad
sudo setcap cap_net_admin,cap_net_raw+ep target/debug/sherpad
sudo -u sherpa SHERPA_ADMIN_PASSWORD=$SHERPA_ADMIN_PASS target/debug/sherpad start --foreground
