[package]
name = "container"
version = "0.3.78"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

# Errors
anyhow = { workspace = true }

# Logging
tracing = { workspace = true }

# Containers
# oci-client = "0.15"
bollard = { workspace = true }

# De/Compression
async-compression = { workspace = true }

# Async
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "fs", "io-util"] }
tokio-util = { workspace = true, features = ["codec"] }
futures = { workspace = true }
futures-util = { workspace = true }
