[package]
name = "db"
version = "0.3.78"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

# Errors
anyhow = { workspace = true }

# Networking
ipnet = { workspace = true }
jiff = { workspace = true }

# Logging
tracing = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
surrealdb = "3.0.0"
surrealdb-types = "3.0.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
