[package]
name = "shared"
version = "0.3.78"
edition = "2024"

[dependencies]
toml = { workspace = true }

# File system
shellexpand = "3.1.0"

# Errors
anyhow = { workspace = true }
thiserror = "2.0.17"

# Logging
tracing = { workspace = true }

# Encoding/decoding
base64 = { workspace = true }
md5 = "0.7.0"
sha2 = "0.10.8"
twox-hash = "2.0.0"

# Generate SSH keys
ssh-key = { workspace = true }

# Random number generator
rand = { workspace = true }
petname = "2.0.2"

# Authentication
argon2 = "0.5"
regex = { workspace = true }
jiff = { workspace = true }

# IP Addressing
ipnet = { workspace = true, features = ["serde"] }
getifaddrs = { version = "0.6.0", optional = true }

# Home directory detection
dirs = { workspace = true }

reqwest = { workspace = true }

# TLS support
rustls = { workspace = true }
rustls-pki-types = "1.10"
webpki-roots = "0.26"
rustls-pemfile = { workspace = true }

# Certificate parsing
x509-parser = "0.16"
hex = "0.4"
url = { workspace = true }

# Templates
askama = { workspace = true }

# Table formatting
tabled = "0.20.0"

# CLI
clap = { workspace = true }

# Serialization/Deserialization
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
schemars = "1.2.1"

# Enum helpers
strum = { workspace = true }
strum_macros = "0.27"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tempfile = { workspace = true }

[features]
netinfo = ["dep:getifaddrs"]
