[package]
name = "network"
version = "0.3.78"
edition = "2024"

[dependencies]
aya = "0.13.1"
rtnetlink = "0.20.0"
shared = { path = "../shared" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
futures = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
